<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/17 19:25:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeetuser',
  'password' => 'jobetpass',
  'name' => 'doctrine',
)),);
